### PR TITLE
优化柱状图

### PR DESCRIPTION
**Pull request by wtl-tianliang**
允许为柱状图的不同柱体设置不同的颜色，同时兼容之前的写法。
新的柱状图设置为：
series: [{
        color: '#3399FF',
        data: [
          4.56
          , 5
          , {
            color: 'red',
            value: 7.12
          }, {
            color: '#FFDC33',
            value: 6.12
          }],
        format: function (val) {
          if (val > 5 && val < 8) {
            return val
          } else {
            return val
          }
        }
      }]

### CODE REVIEW

**Comment by 498728659** [comment]
柱形图颜色优化下载了怎么调用啊 新手， 之前就是调一个wxcharts.js就可以 但你优化一堆js和组件怎么用啊 我只是替换了 wxcharts 按你的格式放进去 报错的

**Comment by wtlsky** [comment]
下载我这个仓库，然后运行 npm run build 重新编译产生dist文件引入即可

**Comment by wtlsky** [comment]
@498728659 下载我的这个仓库，然后运行npm run build重新生成dist文件，引入你的项目即可

**Comment by iaeolous** [comment]
> @498728659 下载我的这个仓库，然后运行npm run build重新生成dist文件，引入你的项目即可

npm run build报错了怎么办


\> wechat-charts@1.0.0 build C:\Users\Aeolus\Desktop\wx-charts
\> rollup -c && rollup --config rollup.config.prod.js

(!) You have passed an unrecognized option
Unknown input options: entry, format, dest, banner. Allowed options: acorn, acornInjectPlugins, cache, context, experimentalCacheExpiry, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, perf, plugins, preserveEntrySignatures, preserveModules, preserveSymlinks, shimMissingExports, strictDeprecations, treeshake, watch

 → stdout...
[!] Error: You must supply options.input to rollup
Error: You must supply options.input to rollup
    at Graph.generateModuleGraph (C:\Users\Aeolus\AppData\Roaming\npm\node_modules\rollup\dist\shared\rollup.js:18397:19)
    at async Graph.build (C:\Users\Aeolus\AppData\Roaming\npm\node_modules\rollup\dist\shared\rollup.js:18361:9)
    at async rollupInternal (C:\Users\Aeolus\AppData\Roaming\npm\node_modules\rollup\dist\shared\rollup.js:19326:9)
    at async build (C:\Users\Aeolus\AppData\Roaming\npm\node_modules\rollup\dist\bin\rollup:1436:20)
    at async runRollup (C:\Users\Aeolus\AppData\Roaming\npm\node_modules\rollup\dist\bin\rollup:1610:21)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechat-charts@1.0.0 build: \`rollup -c && rollup --config rollup.config.prod.js\`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wechat-charts@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aeolus\AppData\Roaming\npm-cache\_logs\2020-07-09T06_20_50_892Z-debug.log

**Pull request closed without merging**
